"""Initial schema

Revision ID: ddf9a2c9bcb3
Revises: 
Create Date: 2026-09-09 20:46:38.366420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf9a2c9bcb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('geographic_scope', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('dataset_date', sa.String(), nullable=False),
    sa.Column('provenance', sa.Enum('VERIFIED', 'CALCULATED', 'ESTIMATED', 'SEEDED_DEMO', 'ASSUMPTION', 'AI_INTERPRETATION', name='provenance'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_indicator'), 'activities', ['indicator'], unique=False)
    op.create_table('businesses',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('dataset_date', sa.String(), nullable=False),
    sa.Column('provenance', sa.Enum('VERIFIED', 'CALCULATED', 'ESTIMATED', 'SEEDED_DEMO', 'ASSUMPTION', 'AI_INTERPRETATION', name='provenance'), nullable=False),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_index(op.f('ix_businesses_business_id'), 'businesses', ['business_id'], unique=False)
    op.create_index(op.f('ix_businesses_category'), 'businesses', ['category'], unique=False)
    op.create_table('demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('geographic_scope', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('dataset_date', sa.String(), nullable=False),
    sa.Column('provenance', sa.Enum('VERIFIED', 'CALCULATED', 'ESTIMATED', 'SEEDED_DEMO', 'ASSUMPTION', 'AI_INTERPRETATION', name='provenance'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographics_id'), 'demographics', ['id'], unique=False)
    op.create_index(op.f('ix_demographics_indicator'), 'demographics', ['indicator'], unique=False)
    op.create_index(op.f('ix_demographics_location_id'), 'demographics', ['location_id'], unique=False)
    op.create_table('financial_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_assessments_id'), 'financial_assessments', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('hierarchy', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_location_id'), 'locations', ['location_id'], unique=False)
    op.create_table('places',
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('dataset_date', sa.String(), nullable=False),
    sa.Column('provenance', sa.Enum('VERIFIED', 'CALCULATED', 'ESTIMATED', 'SEEDED_DEMO', 'ASSUMPTION', 'AI_INTERPRETATION', name='provenance'), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index(op.f('ix_places_category'), 'places', ['category'], unique=False)
    op.create_index(op.f('ix_places_place_id'), 'places', ['place_id'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('access_method', sa.String(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('geographic_coverage', sa.String(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('update_frequency', sa.String(), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_sources_source_id'), 'sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_source_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_places_place_id'), table_name='places')
    op.drop_index(op.f('ix_places_category'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_locations_location_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_financial_assessments_id'), table_name='financial_assessments')
    op.drop_table('financial_assessments')
    op.drop_index(op.f('ix_demographics_location_id'), table_name='demographics')
    op.drop_index(op.f('ix_demographics_indicator'), table_name='demographics')
    op.drop_index(op.f('ix_demographics_id'), table_name='demographics')
    op.drop_table('demographics')
    op.drop_index(op.f('ix_businesses_category'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_activities_indicator'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
